### ISSUE TITLE
Ideas for full ImGui `docking` branch support

### ISSUE THREAD

**Issue by ajh123** [raylib-extras/rlImGui#19]
Since 2018 ImGui has had [support for viewports and docking](https://github.com/ocornut/imgui/issues/2109). 

Currently rlImGui, supports docking if you enable it like so:
```c
ImGuiIO& io = ImGui::GetIO();
io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
```

However multiple viewports would be a challenge to implement:
* You need to detect if multi-viewport support is wanted, maybe with a `#define ENABLE_VIEWPORTS`?
* Using [some surgry](https://github.com/raysan5/raylib/wiki/Use-multiple-windows) you can get raylib to use multiple windows!
* Using the `FLAG_WINDOW_UNDECORATED` flag for `SetConfigFlags` we can remove the title bar of the new windows (for the full effect).

Finally, we will have full support of the docking branch. It won't be as simple as it looks, but it would be useful for many rlImGui users.

Maybe rlImGui can have its own `docking` branch which is used to experiment with viewports?

**Comment by JeffM2501** [comment]
I am very aware of the docking branch of ImGui, and yes rlImGui supports it by using that exact code.

I do not intend to support multiple viewports in rlImGui in any way.
Since raylib does not and will not have a multi-window API, any support for viewports would be based on a specific fork. Those instructions are a general guideline and are not an official API. The actual implementation of multiple windows in raylib can vary.

If someone is going to maintain a fork of raylib with a multi-window API, they can also maintain a fork of rlImGui that uses that fork. 

There is no benefit to having code that is reliant on a specific hacked up version of raylib inside of this repository. This is what forks are for. Doubling the maintenance cost of rlImGui for no clear benefit is not worth it.
