### ISSUE TITLE
rendering issue on MacOS with minimal setup

### ISSUE THREAD

**Issue by PhantomCloak** [raylib-extras/rlImGui#36]
Description:
When switching the rlImGui backend, I've encountered a rendering issue where ImGui elements are not rendered beyond an invisible boundary or region which located bottom left of the screen as can be seen in below screenshoots. I've used minimal example that I took from [simple.cpp](https://github.com/raylib-extras/rlImGui/blob/main/examples/simple.cpp) also this issue persist across different setups such as editor.cpp or my own implementation, while still doesn't sure about root of the problem I suspect from underlying OpenGL implementation.

Reproductable Code:
```
#include "raylib.h"
#include "raymath.h"

#include "imgui.h"
#include "rlImGui.h"

int main(int argc, char* argv[])
{
	// Initialization
	//--------------------------------------------------------------------------------------
	int screenWidth = 1280;
	int screenHeight = 800;

	SetConfigFlags(FLAG_MSAA_4X_HINT | FLAG_VSYNC_HINT);
	InitWindow(screenWidth, screenHeight, "raylib-Extras [ImGui] example - simple ImGui Demo");
	SetTargetFPS(144);
	rlImGuiSetup(true);

	// Main game loop
	while (!WindowShouldClose())    // Detect window close button or ESC key
	{
		BeginDrawing();
		ClearBackground(DARKGRAY);

		// start ImGui Conent
		rlImGuiBegin();

		// show ImGui Content
		bool open = true;
		ImGui::ShowDemoWindow(&open);

		// end ImGui Content
		rlImGuiEnd();

		EndDrawing();
		//----------------------------------------------------------------------------------
	}
	rlImGuiShutdown();

	// De-Initialization
	//--------------------------------------------------------------------------------------   
	CloseWindow();        // Close window and OpenGL context
	//--------------------------------------------------------------------------------------

	return 0;
}
```

Screenshots: 

as the position changes rendered area/elements of the imgui window changes as well 

<img width="1392" alt="image" src="https://github.com/raylib-extras/rlImGui/assets/34552014/db1d5b8a-78ee-4bc7-b43e-408c079a9cf5">

<img width="1392" alt="image" src="https://github.com/raylib-extras/rlImGui/assets/34552014/270b05e9-632b-4eca-89e7-60963bf20930">

<img width="1392" alt="image" src="https://github.com/raylib-extras/rlImGui/assets/34552014/e3ee5166-e83d-48d9-a122-6450ae50b354">

Context:
OS: MacOS Ventura 13.5.2
Hardware: M1 Mac
Compiler: Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0

**Comment by JeffM2501** [comment]
Yes, this is an issue with Apple's OpenGL drivers. The stencil buffer does not get set correctly because the OpenGL on Apple does not report the correct sizes in some cases on HighDPI displays. This is the cause of much pain in raylib on MacOS.
There is code in rlImGui that is trying to solve this
https://github.com/raylib-extras/rlImGui/blob/557147b4950fe75582f7dd12afc7191ae525f9fb/rlImGui.cpp#L93

You want to enable the high DPI mode in your config flags, and see if that fixes it.

If not, I don't have a mac and can't test this.

OpenGL is deprecated with Apple and at some point will stop working. Apple is only supporting Metal2/3 in the future.
