### ISSUE TITLE
Is is possible to adapt imgui_impl_raylib.h to use docking branch and using ImGuiConfigFlags_ViewportsEnable?

### ISSUE THREAD

**Issue by ferranferri** [raylib-extras/rlImGui#42]
Hi, as Imgui can be used to make tools, It would be good to get the possibility to config in multiple viewports, like this: https://github.com/ocornut/imgui/wiki/multi-viewports

Is there any chance to get this?

**Comment by JeffM2501** [comment]
I am very familiar with the viewports system in Dear ImGui (my company paid for that system to be created).

Unfortunately raylib itself does not support multiple windows, and that is required by the backend system in order to support multiple viewport. Each viewport is a window. 
Since raylib only supports one window, rlImGui can only support one viewport.

If you need multiple viewports I recommend you don't use raylib itself, use the glfw and opengl backends and use rlgl in standalone mode.

This is not a feature that can be supported with rlImGui and raylib.
